# This is a basic workflow to help you get started with Actions

name: deploy documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      
      - uses: actions/setup-python@v3.1.0
      
      - name: setup python environment
        run: |
          pip install -e .[docs]
          
      - name: generate the docs
        run: |
          mkdir html
          pdoc3 --html --force -o html network_hash_gen
          mv html/network_hash_gen/* docs
          rm -r html
          ls
          ls docs
          
      - name: commit the docs
        run: |
          git branch gh-pages
          git checkout gh-pages
          git config --local user.email "jo+github-actions@swagspace.org"
          git config --local user.name "github-actions[bot]"
          git commit -m "generated documentation" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
